#!/bin/bash

# This script should be executed from the root directory of this project

# Create the output directory
mkdir -p output/
mkdir -p output/cfg
mkdir -p output/amortizations

# The following file is generated by running `sbt package`
brbo_jar="./target/scala-2.12/brbo2-impl_2.12-0.1.jar"

# Jars dependency
lib_jars="lib/deps/*"
# tools.jar is needed for JDK 8, but not JDK 11
tools_jar_wsl="$HOME/.sdkman/candidates/java/current/lib/tools.jar"
tools_jar_docker="/usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar"

classpath=".:$lib_jars:$brbo_jar:$tools_jar_wsl:$tools_jar_docker"

set -x
timeout --preserve-status --kill-after 3s 8m java -Dlog4j.configurationFile="src/resources/log4j2.properties" -cp $classpath brbo.BrboMain "${@:1}"
